export const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'http://127.0.0.1:54321'
export const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'missing-anon-key'
export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
export const openaiApiKey = process.env.OPENAI_API_KEY || ''
export const openaiImageModel = process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1.5'
